# Generated by Django 5.1.2 on 2025-05-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default="'temp_login_' + str(id)", error_messages={'unique': 'A user with that login already exists.'}, help_text='Required. 30 characters or fewer. Used for authentication.', max_length=30, unique=True, verbose_name='login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Displayed as user name.', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
