# Generated by Django 5.1.2 on 2025-05-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_user_options_user_login_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Displayed as user name.', max_length=150, verbose_name='username'),
        ),
    ]
