# Generated by Django 5.1.2 on 2025-06-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAcc',
            fields=[
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modify_dttm', models.DateTimeField()),
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'payment_acc',
            },
        ),
        migrations.CreateModel(
            name='PaymentOperations',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reciever_id', models.IntegerField()),
                ('count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('initiator', models.IntegerField(blank=True, null=True)),
                ('task_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_operations',
            },
        ),
    ]
