# Generated by Django 5.1.2 on 2025-06-02 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_initiator_id', models.IntegerField()),
                ('task_desc', models.TextField()),
                ('complexity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('task_name', models.CharField(max_length=255)),
                ('create_dttm', models.DateTimeField()),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='task.task')),
                ('task_status', models.CharField(choices=[('CREATED', 'Создана'), ('IN_PROGRESS', 'В работе'), ('ON_END', 'Завершена'), ('ENDED', 'Окончена')], max_length=20)),
                ('executor_id', models.IntegerField(blank=True, null=True)),
                ('create_dttm', models.DateTimeField()),
                ('modify_dttm', models.DateTimeField()),
                ('end_dttm', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_status',
            },
        ),
        migrations.CreateModel(
            name='TaskVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor_id', models.IntegerField()),
                ('create_dttm', models.DateTimeField()),
                ('is_selected', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
            options={
                'db_table': 'task_votes',
                'constraints': [models.UniqueConstraint(fields=('task', 'executor_id'), name='unique_task_executor')],
            },
        ),
    ]
